Documentation

diff --git a/.github/workflows/build-docs.yml b/.github/workflows/build-docs.yml
--- a/.github/workflows/build-docs.yml
+++ b/.github/workflows/build-docs.yml
@@ -9,7 +9,30 @@ jobs:
     runs-on: ubuntu-latest
     container: debian:buster-slim
     steps:
-      - uses: actions/checkout@v2
-      - name: Run build script for Sphinx pages
-        run: "docs/buildsite.sh"
-        shell: bash
+      - name: Checkout
+        uses: actions/checkout@v1
+        with:
+          ref:  main
+      - name: Sphinx Build
+        uses: ammaraskar/sphinx-action@0.4
+        with:
+          docs-folder: "docs/"
+      - name: Commit documentation changes
+        run: |
+          apt update
+          apt install -y git
+          git clone https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/build/html/* tmp/mrdpf/
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: tmp/mrdpf/
+          github_token: ${{ secrets.GITHUB_TOKEN }}
